### ISSUE TITLE
move to Poise for service definition/management

### ISSUE THREAD

**Issue by mburns** [mburns/paramount#64]
- [ ] all `paramount`-configured services are Poise
- [ ] update upstream coookbooks where possible
## 
- [ ] prefer `runit`
- [ ] avoid `bluepill`, `upstart`
